name: 'WebApp Console Log Action'
description: 'An action to capture and post console logs from a web application'
author: 'Jannis Hell (@Primajin)'
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  webapp-url:
    description: 'The URL of the web application'
    required: true
  wait-time:
    description: 'The wait time before capturing logs'
    required: false
    default: 2500
  show-emoji:
    description: 'Whether to show emojis in the output'
    required: false
    default: true
  min-log-level:
    description: 'The minimum log level to capture (verbose, info, warning, error)'
    required: false
    default: 'verbose'
  max-log-level:
    description: 'The maximum log level to allow (verbose, info, warning, error). Set to error to disable failing.'
    required: false
    default: 'info'
  comment-tag:
    description: 'The tag to use for the comment - so it can be replaced, you may pass empty string to always post a new comment'
    required: false
    default: 'console-log'
  headline:
    description: 'The headline for the console logs comment'
    required: false
    default: 'Console Logs'
outputs:
  console:
    description: 'The captured console log'
runs:
  using: 'node20'
  main: 'dist/index.js'
