name: 'WebApp Console Log Action'
description: 'An action to capture and post console logs from a web application'
author: 'Jannis Hell (@Primajin)'

branding:
  icon: 'clipboard'
  color: 'blue'

inputs:
  artifact-name:
    description: 'The name of the artifact to download'
    required: false
  comment-tag:
    description: 'The tag to use for the comment - so it can be replaced, you may pass empty string to always post a new comment'
    required: false
    default: 'console-log'
  headline:
    description: 'The headline for the console logs comment'
    required: false
    default: 'Console Logs'
  max-log-level:
    description: 'The maximum log level to allow (verbose, info, warning, error). Set to error to disable failing.'
    required: false
    default: 'info'
  min-log-level:
    description: 'The minimum log level to capture (verbose, info, warning, error)'
    required: false
    default: 'verbose'
  port:
    description: 'The port to run the http-server on'
    required: false
  regexp-error:
    description: 'Regular expression pattern to filter error logs'
    required: false
  regexp-info:
    description: 'Regular expression pattern to filter info logs'
    required: false
  regexp-verbose:
    description: 'Regular expression pattern to filter verbose logs'
    required: false
  regexp-warning:
    description: 'Regular expression pattern to filter warning logs'
    required: false
  show-emoji:
    description: 'Whether to show emojis in the output'
    required: false
    default: 'true'
  wait-time:
    description: 'The wait time before capturing logs'
    required: false
    default: '2500'
  webapp-url:
    description: 'The URL of the web application'
    required: true

outputs:
  console:
    description: 'The captured console log'
    value: ${{ steps.capture-console.outputs.console }}

runs:
  using: 'composite'
  steps:
    - name: Check artifact name requirement
      run: |
        if [[ "${{ inputs.webapp-url }}" == *"http://localhost"* && -z "${{ inputs.artifact-name }}" ]]; then
          echo "Error: artifact-name is required when webapp-url points to localhost."
          exit 1
        fi
      shell: bash

    - name: Set port to 3000 if webapp-url is localhost and port is not set
      id: set-port
      run: |
        if [[ "${{ inputs.webapp-url }}" == *"http://localhost"* && -z "${{ inputs.port }}" ]]; then
          echo "port=3000" >> $GITHUB_ENV
        else
          echo "port=${{ inputs.port }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Download artifact
      if: contains(inputs.webapp-url, 'http://localhost')
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: app

    - name: Run http-server in the background
      if: contains(inputs.webapp-url, 'http://localhost')
      run: npx http-server app/ -p ${{ env.port }} &
      shell: bash

    - name: Set ACTION_PATH environment variable
      run: echo "ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ env.ACTION_PATH }}

    - name: Setup Chromium
      run: npx playwright install chromium
      shell: bash
      working-directory: ${{ env.ACTION_PATH }}

    - name: Execute Capture Script
      run: node capture-console.mjs
      shell: bash
      working-directory: ${{ env.ACTION_PATH }}
      env:
        MAX_LOG_LEVEL: ${{ inputs.max-log-level }}
        MIN_LOG_LEVEL: ${{ inputs.min-log-level }}
        PORT: ${{ env.port }}
        REGEXP_ERROR: ${{ inputs.regexp-error }}
        REGEXP_INFO: ${{ inputs.regexp-info }}
        REGEXP_VERBOSE: ${{ inputs.regexp-verbose }}
        REGEXP_WARNING: ${{ inputs.regexp-warning }}
        WAIT_TIME: ${{ inputs.wait-time }}
        WEBAPP_URL: ${{ inputs.webapp-url }}

    - name: Set Output
      id: capture-console
      run: |
        echo 'console<<EOF' >> $GITHUB_OUTPUT
        jq -c . console_output.json >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ env.ACTION_PATH }}

    - name: Format Console Output  # Step to format the console output into GitHub Flavored Markdown
      id: format_console_output
      run: |
        # Create a markdown file and add a main heading
        echo "# ${{ inputs.headline }}" > formatted_console_output.md
        # Loop through each key in the JSON file
        for key in $(jq -r 'keys[]' console_output.json); do
          # Capitalize the first character of the key
          capitalized_key=$(echo "$key" | awk '{print toupper(substr($0, 1, 1)) tolower(substr($0, 2))}')
          # Add a subheading for each log level with matching emoji if show-emoji is true
          if [ "${{ inputs.show-emoji }}" = "true" ]; then
            case "$key" in
              verbose) emoji="💬" ;;
              info) emoji="ℹ️" ;;
              warning) emoji="⚠️" ;;
              error) emoji="❌" ;;
              *) emoji="" ;;
            esac
            echo "## $emoji $capitalized_key" >> formatted_console_output.md
          else
            echo "## $capitalized_key" >> formatted_console_output.md
          fi
          # Add a code block for each log message
          echo '```' >> formatted_console_output.md
          # Add each log message
          jq -r --arg key "$key" '.[$key][]' console_output.json >> formatted_console_output.md
          # Close the code block
          echo '```' >> formatted_console_output.md
          # Add an empty line for better readability when editing
          echo "" >> formatted_console_output.md
        done
      shell: bash
      working-directory: ${{ env.ACTION_PATH }}

    - name: Post Console Output to PR
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v3
      with:
        comment-tag: ${{ inputs.comment-tag }}
        file-path: ${{ env.ACTION_PATH }}/formatted_console_output.md
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: Check if action should fail
      run: |
        if [ "$SHOULD_FAIL_ACTION" = "true" ]; then
          echo "Action should fail due to log level threshold."
          exit 1
        fi
      shell: bash
      env:
        SHOULD_FAIL_ACTION: ${{ env.SHOULD_FAIL_ACTION }}
