name: "Should pass"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install a server and serve a file with console logs. Then post console to PR.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run http-server on port 3000 in the background
        run: npx http-server ./ -p 3000 &
      - name: Use WebApp Console Log Action
        uses: ./
        with:
          comment-tag: console-log2
          headline: No emojis, min log level warning, max log level error
          max-log-level: error
          min-log-level: warning
          show-emoji: false
          wait-time: 5
          webapp-url: 'http://localhost:3000'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
